# Урок 2

In [1]:
import numpy as np
from numpy.linalg import norm

### 1. Найти скалярное произведение векторов $x, y \in \mathbb{R} :$

a) $x=(0, -3, 6), y=(-4, 7, 9)$   
б) $x=(7, -4, 0, 1), y=(-3, 1, 11, 2)$

In [2]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
33


In [3]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
-23


### 2. Найти нормы векторов  (4, 2, 4)  и  (12, 3, 4)  и угол между ними.

In [4]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

print(f'l1a норма вектора a:\n{norm(a, ord=1)}')
print(f'l2a норма вектора a:\n{norm(a, ord=2)}')

print(f'l1b норма вектора b:\n{norm(b, ord=1)}')
print(f'l2b норма вектора b:\n{norm(b, ord=2)}')

cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

l1a норма вектора a:
10.0
l2a норма вектора a:
6.0
l1b норма вектора b:
19.0
l2b норма вектора b:
13.0
Косинус угла между a и b: 0.90
Угол между a и b: 0.46


### 3. Будет ли линейное пространство евклидовым, если за скалярное произведение принять:
а) произведение длин векторов;   
б) утроенное обычное скалярное произведение векторов?

Для евклидова пространства справедливы аксиомы:    
1) $(x, y)=(y, x)$    
2) $(\lambda x, y)=\lambda(x, y)$    
3) $\left(x_{1}+x_{2}, y\right)=\left(x_{1}, y\right)+\left(x_{2}, y\right)$    
4) $(x, x) \geq 0,$ причем $(x, x)=0 \Leftrightarrow x=0$

Проверим справедливость аксиом для произведения длин векторов.

$\sqrt{x_{i}^{2}+x_{j}^{2}+x_{k}^{2}...} \cdot \sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} = \sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} \cdot \sqrt{x_{i}^{2}+x_{j}^{2}+x_{k}^{2}...} 
$   
Равенство справедливо

$\left(\lambda \cdot \sqrt{x_{i}^{2}+x_{j}^{2}+x_{k}^{2}...}\right) \cdot \sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} = \lambda \cdot \left(\sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} \cdot \sqrt{x_{i}^{2}+x_{j}^{2}+x_{k}^{2}...}\right)
$   
Равенство справедливо

$\sqrt{(x_{i1}+x_{i2})^{2}+(x_{j1}+x_{j2})^{2}+(x_{k1}+x_{k2})^{2}...} \cdot \sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} = 
\sqrt{x_{i1}^{2}+x_{j1}^{2}+x_{k1}^{2}...}\sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...} + \sqrt{x_{i2}^{2}+x_{j2}^{2}+x_{k2}^{2}...}\sqrt{y_{i}^{2}+y_{j}^{2}+y_{k}^{2}...}
$   
Равенство несправедливо

Ответ:  если за скалярное произведение принять произведение длин векторов, линейное пространство не будет евклидовым.

Проверим справедливость аксиом для утроенного скалярного произведения векторов.

$3(x, y) = 3x_{1} y_{1}+3x_{2} y_{2}+\cdots+3x_{n} y_{n}=3(y, x)$ - верно

$3(𝜆𝑥, 𝑦) = (3𝜆𝑥, 𝑦) = 3𝜆(𝑥, 𝑦)$ - верно

$3(𝑥_1+𝑥_2, 𝑦)=(3𝑥_1, 𝑦)+(3𝑥_2, 𝑦)$ - верно

$3(𝑥,𝑥)≥0$ - верно

Ответ:  линейное пространство будет евклидовым, если за скалярное произведение принять утроенное скалярное произведение.

### 4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3} :$

a) $(1, 0, 0), (0, 0, 1)$   
б) $(1 / \sqrt{2}, -1 / \sqrt{2}, 0), (1 / \sqrt{2}, 1 / \sqrt{2}, 0),(0, 0, 1) ;$   
B) $(1 / 2, -1 / 2, 0), (0, 1 / 2, 1 / 2), (0, 0, 1) ;$   
r) $(1, 0, 0), (0, 1, 0), (0, 0, 1) ?$

В конечномерном евклидовом пространстве базис $\left\{e_{1}, e_{2}, \dots, e_{n}\right\}$  называется ортонормированным, если $\left(e_{i}, e_{j}\right) = 0$  $\forall i \neq j$ и  $\left(e_{i}, e_{i}\right) = 1$  $\forall i \in[1, n]$.

In [5]:
def orthonormal_basis(a, b, c):
    if np.dot(a, b) == 0 and np.dot(b, c) == 0 and np.dot(c, a) == 0 and np.dot(a, a) == 1 and np.dot(b, b) == 1 and np.dot(c, c) ==1:
        return f'Векторы {a}, {b}, {c} образуют ортонормированный базис'
    else:
        return f'Векторы {a}, {b}, {c} не образуют ортонормированный базис'

In [6]:
a = np.array([1, 0, 0])
b = np.array([0, 0, 1])
# 2 вектора не образуют ортонормированный базис трехмерного пространства.

In [7]:
a = np.array([1 * 2 ** -0.5])
b = np.array([-1 * 2 ** -0.5])
c = np.array([0, 0, 1])
orthonormal_basis(a, b, c)

'Векторы [0.70710678], [-0.70710678], [0 0 1] не образуют ортонормированный базис'

In [8]:
a = np.array([1 / 2, -1 / 2, 0])
b = np.array([0, 1 / 2, 1 / 2])
c = np.array([0, 0, 1])
orthonormal_basis(a, b, c)

'Векторы [ 0.5 -0.5  0. ], [0.  0.5 0.5], [0 0 1] не образуют ортонормированный базис'

In [9]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])
orthonormal_basis(a, b, c)

'Векторы [1 0 0], [0 1 0], [0 0 1] образуют ортонормированный базис'

# Урок 3

In [10]:
import numpy as np

### 1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

Чтобы умножить матрицу А на матрицу В необходимо, чтобы число столбцов матрицы  A  было равно числу строк матрицы  B.

In [11]:
def product(a, b):
    if a.shape[1] == b.shape[0]:
        return f'Произведение матриц А и В определены, размерность полученной матрицы {a.shape[0]}x{b.shape[1]}'
    return f'Произведение матриц А и В не определены'

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

In [12]:
a = np.zeros((4, 2))
b = np.zeros((4, 2))
product(a, b)

'Произведение матриц А и В не определены'

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

In [13]:
a = np.zeros((2, 5))
b = np.zeros((5, 3))
product(a, b)

'Произведение матриц А и В определены, размерность полученной матрицы 2x3'

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

In [14]:
a = np.zeros((8, 3))
b = np.zeros((3, 8))
product(a, b)

'Произведение матриц А и В определены, размерность полученной матрицы 8x8'

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

In [15]:
a = np.zeros((4, 4))
b = np.zeros((4, 4))
product(a, b)

'Произведение матриц А и В определены, размерность полученной матрицы 4x4'

### 2. Найти сумму и произведение матриц

$A=\left(\begin{array}{cc}{1} & {-2} \\ {3} & {0}\end{array}\right)$  и $ B=\left(\begin{array}{cc}{4} & {-1} \\ {0} & {5}\end{array}\right)$

$A + B = \left(\begin{array}{cc}{1+4} & {-2-1} \\ {3+0} & {0+5}\end{array}\right)=\left(\begin{array}{cc}{5} & {-3} \\ {3} & {5}\end{array}\right)$

$A \cdot B = \left(\begin{array}{cc}{1\cdot4-2\cdot0} & {1\cdot(-1)-2\cdot5} \\ 
{3\cdot4+0\cdot0} & {3\cdot(-1)+0\cdot5}\end{array}\right)=\left(\begin{array}{cc}{4} & {-11} \\ {12} & {-3}\end{array}\right)$

In [16]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b

array([[ 5, -3],
       [ 3,  5]])

In [17]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц

$A=\left(\begin{array}{cc}{1} & {7} \\ {3} & {-6}\end{array}\right), B=\left(\begin{array}{cc}{0} & {5} \\ {2} & {-1}\end{array}\right), C=\left(\begin{array}{cc}{2} & {-4} \\ {1} & {1}\end{array}\right)$

$3A−2B+4C = 3\left(\begin{array}{cc}{1} & {7} \\ {3} & {-6}\end{array}\right)- 2\left(\begin{array}{cc}{0} & {5} \\ {2} & {-1}\end{array}\right) +4\left(\begin{array}{cc}{2} & {-4} \\ {1} & {1}\end{array}\right) =
$

$=\left(\begin{array}{cc}{3} & {21} \\ {9} & {-18}\end{array}\right)- \left(\begin{array}{cc}{0} & {10} \\ {4} & {-2}\end{array}\right) +\left(\begin{array}{cc}{8} & {-16} \\ {4} & {4}\end{array}\right) = \left(\begin{array}{cc}{11} & {-5} \\ {9} & {-15}\end{array}\right)$


In [18]:
a = np.array([[1, 7], [3, -7]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a - 2 * b + 4 * c

array([[ 11,  -5],
       [  9, -15]])

### 4. Дана матрица  

$A=\left(\begin{array}{cc}{4} & {1} \\ {5} & {-2} \\ {2} & {3}\end{array}\right)$

Вычислить $A A^{T}$  и  $A^{T} A$

$AA^T = \left(\begin{array}{cc}{4} & {1} \\ {5} & {-2} \\ {2} & {3}\end{array}\right) \cdot \left(\begin{array}{cc}{4} & {5} & {2} \\ {1} & {-2} & {3}\end{array}\right)=
$

$=\left(\begin{array}{cc}{4\cdot4+1\cdot1} & {4\cdot5 +1\cdot(-2)} & {4\cdot2+1\cdot3} \\ {5\cdot4 +2\cdot1} & {5\cdot5-2\cdot(-2)} & {5\cdot2-2\cdot3} \\ {2\cdot4+3\cdot1} & {2\cdot5+3\cdot(-2)} & {2\cdot2+3\cdot3}\end{array}\right)=
\left(\begin{array}{cc}{17} & {18} & {11} \\ {22} & {29} & {4} \\ {11} & {4} & {13}\end{array}\right)$

In [19]:
a = np.array([[4, 1], [5, -2], [2, 3]])
np.dot(a, a.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$ A^{T}A=\left(\begin{array}{ccc}{4} & {5} & {2} \\ {1} & {-2} & {3}\end{array}\right) \cdot\left(\begin{array}{cc}{4} & {1} \\ {5} & {-2} \\ {2} & {3}\end{array}\right) =$

$=\left(\begin{array}{cc}{4\cdot4+5\cdot5+2\cdot2} & {4\cdot1 +5\cdot(-2)+2\cdot3}  \\ 
{1\cdot4 -2\cdot5 +3\cdot2} &{1\cdot1 -2\cdot(-2) +3\cdot3} \end{array}\right)=\left(\begin{array}{cc}{45} & {0}  \\ 
{0} &{14} \end{array}\right)
$

In [20]:
np.dot(a.T, a)

array([[45,  0],
       [ 0, 14]])